### ISSUE TITLE
朋友，你好，IndexBar能升级到androidx么？

### ISSUE THREAD

**Issue by hegelsu** [Vanish136/IndexBar#2]
好像Demo更新了，谢谢。

**Comment by hegelsu** [comment]
你看下有没有这个Bug，第一次设置5个过滤字母的时候，它是在右上角紧凑着显示的，然后再次设置5个的时候发现它分开来显示了

**Comment by LwkCoder** [comment]
我无法复现出你说的这种情况  我设置了只有5个字母仍然是正常的

**Comment by hegelsu** [comment]
indexbar所在界面是一个Activity，刚开始是设置5个字母，然后我点击了其中一个item项打开了一个新的activity，然后再返回了有indexbar的界面，然后再下拉刷新，重新计算IndexBar的字母(此时任然是5个)，然后重新设置了字母源，这时就变了

**Comment by LwkCoder** [comment]
我还是复现不出来... 
我也没搞懂你说的这个问题
你是期望什么情况才是正常的？

**Comment by LwkCoder** [comment]
505515031
方便的话可以加QQ详述

**Comment by hegelsu** [comment]
重新搞了一次，又可以了，谢了。你的QQ是拒绝加入的哈。

**Comment by hegelsu** [comment]
再提个需求，当只有5个字母，即只有少量的时候，能否居中显示

**Comment by LwkCoder** [comment]
QQ验证已开放
这个库内部的measure逻辑较为简单，要实现你说的这种居中得重构内部测量逻辑，未来有空的话弄一下，短期内暂时做不了哈，有其他计划在进行中。

**Comment by LwkCoder** [comment]
我临时优化了一点，当宽度为wrap-content时会自动计算合适宽度，高度为wrap-content时值取所有char高度之和，应该能满足你现在的要求了。未来如果有空我会再次优化整个控件。
